# Generated by Django 4.0.3 on 2022-03-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('ds_name', models.CharField(max_length=40)),
                ('edit_link', models.CharField(max_length=150)),
                ('other_links', models.CharField(max_length=150)),
                ('result', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gang/static/img/members')),
                ('name', models.CharField(max_length=60)),
                ('yt_link', models.CharField(max_length=150)),
                ('ins_link', models.CharField(max_length=150)),
                ('ds_tag', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
